[build]
command = "npm run build"
publish = "dist"

[env]
[env.production]
  VITE_API_URL = "https://carrer-portal.vercel.app/api"
  VITE_SUPABASE_URL = "https://zfnneiaojxwnychcrfdi.supabase.co"
  VITE_SUPABASE_ANON_KEY = "sb_publishable_oJMWCmUSK5O21QK8tgypJA_qZpLadfq"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
